workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    scripts:
      - name: Build and package
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
