workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: |
          brew install --cask cocoapods
          flutter pub get
      - name: Build and package
        script: |
          flutter clean
          flutter build ios --release --no-codesign
          echo "Listing build output:"
          ls -la build/ios/iphoneos
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
